SELECT 
       c.[CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,c.[FirstName]
      --,[MiddleName]
      ,c.[LastName]
      ,c.[FirstName]+' '+ c.[LastName] as [FullName]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      --,[Gender]
      ,CASE c.Gender WHEN 'M' THEN 'MALE' ELSE 'FEMALE' END as [Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,c.[DateFirstPurchase] as firstDateOfPurchase 
      --,[CommuteDistance]
      ,g.city as [customerCity]
  FROM dbo.DimCustomer AS c 
    LEFT JOIN dbo.DimGeography as g on g.GeographyKey = c.GeographyKey
ORDER BY CustomerKey ASC
